---
title: "Writing Function"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)

library(p8105.datasets)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.color = "viridis",
  ggplots.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_continuous = scale_fill_viridis_d

```

## Do something simple

```{r}
x_vec = rnorm(30, mean = 5, sd = 3)

(x_vec - mean(x_vec)) / sd(x_vec)
```

I want a function to compute z-score

```{r}
z_score = function(x) {
  
  if(!is.numeric(x)) {
    stop("Imput must be numeric")
  }
  
  if(length(x) < 3) {
    stop("Imput must have at least three numbers")
  }
  
  z = (x - mean(x)) / sd(x)
  
  return(z)
}

z_score(x_vec)
```

Try my function on some other things. This should give errors.

```{r, error = TRUE}
z_score(3)
z_score("my name is jeff")
z_score(c(TRUE, TRUE, FALSE, TRUE))
```


## Multiple outputs

```{r}
mean_and_sd= function(x) {
  
  if(!is.numeric(x)) {
    stop("Imput must be numeric")
  }
  
  if(length(x) < 3) {
    stop("Imput must have at least three numbers")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )

}


```

Check that the function works

```{r}
x_vec = rnorm(100, mean =3, sd = 4)
mean_and_sd(x_vec)
```

## Multiple inputs

I'd like to do this with a function.

```{r}
sim_data = 
  tibble(
    x = rnorm(n = 100, mean = 4, sd = 3)
  )

sim_data %>% 
  summarize(
    mean = mean(x),
    sd = sd(x)
  )
```

```{r}
sim_mean_sd = function(samp_size, mu = 3, sigma = 3) {
  
  sim_data = 
    tibble(
      x = rnorm(n = samp_size, mean = mu, sd = sigma)
  )

sim_data %>% 
  summarize(
    mean = mean(x),
    sd = sd(x)
  )
}
```

```{r}
sim_mean_sd(100, 6, 3)
sim_mean_sd(samp_size = 100, mu = 6, sigma = 3)
sim_mean_sd(samp_size = 100)
```


